import { chromium } from 'playwright';
import nodemailer from 'nodemailer';
import pool from '../config/database.js';
import { GoogleGenerativeAI } from '@google/generative-ai';

// Load settings from DB scoped by company_id
async function getSettings(company_id) {
  const result = await pool.query('SELECT key, value FROM system_settings WHERE company_id = $1', [company_id]);
  const s = {};
  result.rows.forEach(r => { s[r.key] = r.value; });
  return s;
}

// Create transporter from saved SMTP settings
async function createTransporter(s) {
  if (!s.smtp_host || !s.smtp_user || !s.smtp_pass) {
    throw new Error('SMTP not configured. Please set SMTP Host, User, and Password in System Config.');
  }
  return nodemailer.createTransport({
    host: s.smtp_host,
    port: parseInt(s.smtp_port) || 587,
    secure: parseInt(s.smtp_port) === 465,
    auth: { user: s.smtp_user, pass: s.smtp_pass },
  });
}

export async function runAgent(company_id) {
  const s = await getSettings(company_id);
  
  const targetUrl = s.agent_target_url;
  const aiPrompt = s.agent_ai_prompt;
  const targetEmail = s.agent_target_email;
  const geminiApiKey = s.agent_gemini_api_key;

  if (!targetUrl || !aiPrompt || !targetEmail) {
    throw new Error('Agent is not fully configured. Please set Target URL, AI Prompt, and Target Email.');
  }

  if (!geminiApiKey) {
    throw new Error('Gemini API Key is missing. Please add it to the AI Agent settings.');
  }

  let browser = null;
  let rawPageText = '';
  let finalAiResponse = '';

  try {
    // 1. Launch Playwright and scrape the raw page text
    browser = await chromium.launch({ headless: true });
    const page = await browser.newPage();
    
    // Navigate to the target URL
    await page.goto(targetUrl, { waitUntil: 'domcontentloaded', timeout: 30000 });
    
    // Wait a brief moment for dynamic content
    await page.waitForTimeout(3000); 
    
    // Extract the visible text of the entire body
    rawPageText = await page.evaluate(() => document.body.innerText);

    if (!rawPageText || rawPageText.trim().length === 0) {
      throw new Error('No visible text found on the page to analyze.');
    }

  } catch (error) {
    console.error('Playwright scraping error:', error);
    throw new Error(`Error during web scraping: ${error.message}`);
  } finally {
    if (browser) {
      await browser.close();
    }
  }

  try {
    // 2. Use Gemini AI to process the raw text based on the user's prompt
    const genAI = new GoogleGenerativeAI(geminiApiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

    const systemInstruction = `
You are an intelligent web scraping assistant.
You will be provided with the raw text content of a webpage, followed by a user's instruction.
Your task is to analyze the text and fulfill the user's instruction exactly as asked.
Keep your response concise, accurate, and properly formatted.

User Instruction: ${aiPrompt}
`;

    const result = await model.generateContent([
      systemInstruction,
      "\n\n--- RAW WEBPAGE TEXT START ---\n",
      rawPageText.substring(0, 40000), // Limit to avoid exceeding context window if massive
      "\n--- RAW WEBPAGE TEXT END ---\n"
    ]);

    finalAiResponse = result.response.text();

  } catch (error) {
    console.error('Gemini AI processing error:', error);
    throw new Error(`Failed to process text with Gemini AI: ${error.message}`);
  }

  // 3. Send the email with the AI-processed data
  try {
    const transporter = await createTransporter(s);
    
    // We convert markdown-like AI output to simple HTML by wrapping in <pre> or simple replacements
    // (For this version, a <pre> block works perfectly for preserving list spacing)
    const htmlContent = `
      <h2>AI Agent Scraping Result</h2>
      <p><strong>Target URL:</strong> <a href="${targetUrl}">${targetUrl}</a></p>
      <p><strong>Your Instruction:</strong> ${aiPrompt}</p>
      <hr />
      <h3>AI Extracted Content:</h3>
      <div style="background: #f4f4f4; padding: 15px; border-radius: 5px; font-family: Arial, sans-serif; white-space: pre-wrap; line-height: 1.5;">${finalAiResponse}</div>
      <hr />
      <p><small>Powered by Gemini AI • Generated by your POS System AI Agent at ${new Date().toLocaleString()}</small></p>
    `;

    await transporter.sendMail({
      from: `"${s.business_name || 'POS AI Agent'}" <${s.smtp_from || s.smtp_user}>`,
      to: targetEmail,
      subject: `AI Agent Extracted Data: ${targetUrl}`,
      html: htmlContent,
    });
    
    return { success: true, message: 'Agent executed successfully and email sent.', scrapedData: finalAiResponse };
  } catch (error) {
    console.error('Email sending error:', error);
    throw new Error(`Data extracted successfully, but failed to send email: ${error.message}`);
  }
}
