import axios from 'axios';
import nodemailer from 'nodemailer';
import pool from '../config/database.js';
import { GoogleGenerativeAI } from '@google/generative-ai';

// Load settings from DB scoped by company_id
async function getSettings(company_id) {
  const result = await pool.query('SELECT key, value FROM system_settings WHERE company_id = $1', [company_id]);
  const s = {};
  result.rows.forEach(r => { s[r.key] = r.value; });
  return s;
}

// Create transporter from saved SMTP settings
async function createTransporter(s) {
  if (!s.smtp_host || !s.smtp_user || !s.smtp_pass) {
    throw new Error('SMTP not configured. Please set SMTP Host, User, and Password in System Config.');
  }
  return nodemailer.createTransport({
    host: s.smtp_host,
    port: parseInt(s.smtp_port) || 587,
    secure: parseInt(s.smtp_port) === 465,
    auth: { user: s.smtp_user, pass: s.smtp_pass },
  });
}

/**
 * Strips HTML tags and collapses whitespace to extract plain readable text.
 * Works without any external parser — pure regex.
 */
function htmlToText(html) {
  return html
    // Remove <script> and <style> blocks entirely
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    // Replace block-level tags with newlines for readability
    .replace(/<\/(p|div|section|article|header|footer|li|tr|td|th|h[1-6]|br)>/gi, '\n')
    // Strip all remaining HTML tags
    .replace(/<[^>]+>/g, ' ')
    // Decode common HTML entities
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    // Collapse multiple spaces/blank lines
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

export async function runAgent(company_id) {
  const s = await getSettings(company_id);

  const targetUrl = s.agent_target_url;
  const aiPrompt = s.agent_ai_prompt;
  const targetEmail = s.agent_target_email;
  const geminiApiKey = s.agent_gemini_api_key;

  if (!targetUrl || !aiPrompt || !targetEmail) {
    throw new Error('Agent is not fully configured. Please set Target URL, AI Prompt, and Target Email.');
  }

  if (!geminiApiKey) {
    throw new Error('Gemini API Key is missing. Please add it to the AI Agent settings.');
  }

  let rawPageText = '';
  let finalAiResponse = '';

  // 1. Fetch the page with axios (no browser needed)
  try {
    const response = await axios.get(targetUrl, {
      timeout: 30000,
      headers: {
        // Mimic a real browser to avoid bot-blocking
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
      },
      // Return raw HTML string
      responseType: 'text',
    });

    rawPageText = htmlToText(response.data);

    if (!rawPageText || rawPageText.trim().length < 10) {
      throw new Error('No readable text could be extracted from the page.');
    }

  } catch (error) {
    console.error('HTTP scraping error:', error.message);
    throw new Error(`Error during web scraping: ${error.message}`);
  }

  // 2. Use Gemini AI to process the raw text based on the user's prompt
  try {
    const genAI = new GoogleGenerativeAI(geminiApiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

    const systemInstruction = `
You are an intelligent web scraping assistant.
You will be provided with the raw text content of a webpage, followed by a user's instruction.
Your task is to analyze the text and fulfill the user's instruction exactly as asked.
Keep your response concise, accurate, and properly formatted.

User Instruction: ${aiPrompt}
`;

    const result = await model.generateContent([
      systemInstruction,
      '\n\n--- RAW WEBPAGE TEXT START ---\n',
      rawPageText.substring(0, 40000), // Limit to avoid exceeding context window
      '\n--- RAW WEBPAGE TEXT END ---\n',
    ]);

    finalAiResponse = result.response.text();

  } catch (error) {
    console.error('Gemini AI processing error:', error);
    throw new Error(`Failed to process text with Gemini AI: ${error.message}`);
  }

  // 3. Send the email with the AI-processed data
  try {
    const transporter = await createTransporter(s);

    const htmlContent = `
      <h2>AI Agent Scraping Result</h2>
      <p><strong>Target URL:</strong> <a href="${targetUrl}">${targetUrl}</a></p>
      <p><strong>Your Instruction:</strong> ${aiPrompt}</p>
      <hr />
      <h3>AI Extracted Content:</h3>
      <div style="background: #f4f4f4; padding: 15px; border-radius: 5px; font-family: Arial, sans-serif; white-space: pre-wrap; line-height: 1.5;">${finalAiResponse}</div>
      <hr />
      <p><small>Powered by Gemini AI • Generated by your POS System AI Agent at ${new Date().toLocaleString()}</small></p>
    `;

    await transporter.sendMail({
      from: `"${s.business_name || 'POS AI Agent'}" <${s.smtp_from || s.smtp_user}>`,
      to: targetEmail,
      subject: `AI Agent Extracted Data: ${targetUrl}`,
      html: htmlContent,
    });

    return { success: true, message: 'Agent executed successfully and email sent.', scrapedData: finalAiResponse };
  } catch (error) {
    console.error('Email sending error:', error);
    throw new Error(`Data extracted successfully, but failed to send email: ${error.message}`);
  }
}
